var button=document.getElementById('button-1')
console.log(button)
var text=document.getElementsByClassName('text')
console.log(text)
var h2=document.getElementsByTagName('h2')
console.log(h2)
var btn2=document.querySelector('#btn2')
console.log(btn2)
var btn3=document.querySelector('.btn3')
console.log(btn3)
var text1=document.querySelectorAll('.text1')
console.log(text1)